apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${applicationName}-pvc
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: ${jenkinsHomeSize} 
  storageClassName: managed-csi
