apiVersion: v1
kind: Service
metadata:
  name: ${applicationName}-service 
spec:
  selector:
    app: jenkins-pod
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 8080 
  type: ClusterIP


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${applicationName}-ingress
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: ${ipRange} 
spec:
  ingressClassName: nginx
  rules:
  - host: ${hostDNS} 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ${applicationName}-service
            port:
              number: 80
  tls:
  - hosts:
    - ${hostDNS} 
    secretName: jenkins-tls-secret
