image | FROM {} 
 | ENV JENKINS_HOME /var/jenkins_home
 | USER root
 | RUN apt-get update
-strip install_deps_src | COPY copydir/{} /
-strip dependencies | COPY copydir/{} /
-strip install_deps_src -strip dependencies | RUN /{} {}; rm /installdeps
-strip dependencies | RUN rm /{}
-strip jenkins_home_src | ADD --chown=jenkins:root copydir/{} /var 
!@ other_files owner -strip src dest | COPY --chown={} copydir/{} {}
 | USER jenkins
